### ISSUE TITLE
rebar3 compilation failed

### ISSUE THREAD

**Issue by the-prksh** [AntidoteDB/antidote-erlang-client#8]
Hello,

I have integrated **antidote-erlang-client** into my Project as 'deps' and while generating release compilation is failing. Here is a log -

> ===> Verifying dependencies...
===> Linking _build/default/lib/antidote_erlang_client to _build/dev1/lib/antidotec_pb
===> Linking _build/default/plugins/meck to _build/dev1/plugins/meck
===> Plugin meck does not export init/1. It will not be used.
===> Linking _build/default/plugins/protobuffs to _build/dev1/plugins/protobuffs
===> Compiling protobuffs
===> Plugin {protobuffs,{git,"git://github.com/basho/erlang_protobuffs.git",
                                    {tag,"0.9.0"}}} not available. It will not be used.
===> Linking _build/default/plugins/rebar3_protobuffs_plugin to _build/dev1/plugins/rebar3_protobuffs_plugin
===> Compiling protobuffs
===> Plugin {rebar3_protobuffs_plugin,
                       {git,
                           "git://github.com/cmkarlsson/rebar3_protobuffs_plugin",
                           {branch,"master"}}} not available. It will not be used.
===> Linking _build/default/plugins/riak_pb_msgcodegen to _build/dev1/plugins/riak_pb_msgcodegen
===> Linking _build/default/lib/cowboy to _build/dev1/lib/cowboy
===> Linking _build/default/lib/antidote_pb_codec to _build/dev1/lib/antidote_pb_codec
===> Linking _build/default/lib/cowlib to _build/dev1/lib/cowlib
===> Linking _build/default/lib/lager to _build/dev1/lib/lager
===> Linking _build/default/lib/ranch to _build/dev1/lib/ranch
===> Linking _build/default/lib/goldrush to _build/dev1/lib/goldrush
===> Compiling cowlib
===> Compiling ranch
===> Compiling goldrush
===> Compiling lager
===> Compiling antidote_pb_codec
===> Compiling antidotec_pb
===> Unable to run pre hooks for 'compile', command 'compile' in namespace 'protobuffs' not found.
Makefile:13: recipe for target 'devrel' failed
make: *** [devrel] Error 1

Anyone know how to fix this ?

- Prakash

**Comment by bieniusa** [comment]
Somehow the dependencies were not loaded in your case.
I had a look at them and cleaned them up :)

Can you try again?
